### ISSUE TITLE
[BUG] _sign_request is failing while using AWSV4SignerAuth with AsyncOpenSearch

### ISSUE THREAD

**Issue by saimedhi** [opensearch-project/opensearch-py#272] opened 2023-01-18 17:57 UTC
### What is the bug?
_sign_request is failing while using AWSV4SignerAuth with AsyncOpenSearch

### What is the expected behavior?
_sign_request should not fail with correct credentials.

<img width="1027" alt="Screenshot 2023-01-18 at 9 55 53 AM" src="https://user-images.githubusercontent.com/117196660/213258140-ef57f30f-6c4c-456b-9a32-746f8e52f213.png">

**Comment by saimedhi** [comment] 2023-01-18 18:05
```
import asyncio
from os import environ
from time import sleep
from urllib.parse import urlparse

from boto3 import Session
from opensearchpy import AWSV4SignerAsyncAuth, AsyncOpenSearch, AsyncHttpConnection

url = urlparse(environ['OPENSEARCH_ENDPOINT'])
region = environ.get('AWS_REGION', 'us-east-1')

credentials = Session().get_credentials()

auth = AWSV4SignerAsyncAuth(credentials, region)

client = AsyncOpenSearch(
  hosts=[{
    'host': url.netloc,
    'port': url.port or 443
  }],
  http_auth=auth,
  use_ssl=True,
  verify_certs=True,
  connection_class=AsyncHttpConnection
)

async def main():
  info = await client.info()
  print(f"{info['version']['distribution']}: {info['version']['number']}")

  index = 'movies'
  await client.indices.create(index=index)


  try:
    document = {'director': 'Bennett Miller', 'title': 'Moneyball', 'year': 2011}
    await client.index(index=index, body=document, id='1', refresh=True)

   sleep(1)

    results = await client.search(body={'query': {'match': {'director': 'miller'}}})
    for hit in results['hits']['hits']:
      print(hit['_source'])

    await client.delete(index=index, id='1')

  finally:
    await client.indices.delete(index=index)
    
      
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.close()
```

**Comment by saimedhi** [comment] 2023-01-18 18:08
@harshavamsi Can you please take a look. Is it because of my code or a bug?

**Comment by dblock** [comment] 2023-01-18 19:58
@saimedhi I don't see anything wrong here at the first glance. Try https://github.com/dblock/opensearch-python-client-demo with your credentials? That code was tested against AWS OpenSearch.

**Comment by saimedhi** [comment] 2023-01-18 20:04
@dblock I tried executing "example.py" file from the repository mentioned above and produced the right output. But I have trouble with async version of it.

**Comment by Xtansia** [comment] 2023-01-18 20:57
Issue looks to be coming from here: https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/helpers/asyncsigner.py#L47
As can be seen in Sai's screenshot the 3rd url that was printed has the query params twice
`https://search-test-pythondemo-stxjfip2i6w6fo77kbiqa7nmyy.us-east-1.es.amazonaws.com/movies/_doc/1?refresh=truerefresh=true`.
Where as the sync signer has this logic for sanitising the URL https://github.com/opensearch-project/opensearch-py/blob/main/opensearchpy/helpers/signer.py#L22-L45

**Comment by dblock** [comment] 2023-01-18 20:58
Help me modify that sample to reproduce this? 

Why can't I import `AWSV4SignerAsyncAuth`? I have `opensearch-py = {git = "https://github.com/opensearch-project/opensearch-py"}` in Pipfile to double-confirm it's the latest rev.

```
Traceback (most recent call last):
  File "/Users/dblock/source/dblock/opensearch-python-client-demo/example.py", line 16, in <module>
    from opensearchpy import AWSV4SignerAsyncAuth, AsyncOpenSearch, AsyncHttpConnection
ImportError: cannot import name 'AWSV4SignerAsyncAuth' from 'opensearchpy' (/Users/dblock/.local/share/virtualenvs/opensearch-python-client-demo-ejYmDdj0/lib/python3.11/site-packages/opensearchpy/__init__.py)
```

**Comment by saimedhi** [comment] 2023-01-18 21:02
I followed these steps:
cloned opensearch-py repo to code dir
cd ~/code/opensearch-py  
pip install -e ".[async]"
cd ~/OS_PY_Demo/opensearch-python-client-demo

**Comment by dblock** [comment] 2023-01-18 21:41
Oh it's extras, added with `opensearch-py = { extras=["async"], version="*" }`

**Comment by dblock** [comment] 2023-01-23 14:30
FYI I can reproduce this by having a `refresh` parameter in `await client.index(index=index, body=document, id='1', refresh=True)`.

**Comment by nhtruong** [comment] 2023-01-24 02:04
This will be fixed in https://github.com/opensearch-project/opensearch-py/pull/279
Root Cause: QueryString is added twice when signing the request:
[here](https://github.com/opensearch-project/opensearch-py/blob/cfb2cf7b60fa37714e48ede5ed6970b417a1995b/opensearchpy/connection/http_async.py#L177) and [here](https://github.com/opensearch-project/opensearch-py/blob/5c1c890f69eea3e1ef897621adca540480967ade/opensearchpy/helpers/asyncsigner.py#L49)

**Closed** 2023-01-24 02:38 UTC
Labels: bug, untriaged
