### ISSUE TITLE
[BUG] http gzip compression cannot be used with the snapshot endpoints

### ISSUE THREAD

**Issue by ofirt-orca** [opensearch-project/opensearch-py#507] opened 2023-09-22 11:48 UTC
### What is the bug?
http gzip compression cannot be used with the snapshot endpoints

### How can one reproduce the bug?
set `http_compress` to `True` and try to restore an encrypted snapshot from s3
you will get the error `Your request: '/_snapshot/cs-automated-enc/<snapshot_id>/_restore' is not allowed due to invalid input parameters.`

### What is the expected behavior?
That it will work and snapshot will be restored

### What is your host/environment?
ubuntu 20.04

### Do you have any screenshots?
No

### Do you have any additional context?
Only when turning off the gzip compression it works well
Other requests to the cluster seem to work fine (compressed or not)
https://docs.aws.amazon.com/opensearch-service/latest/developerguide/gzip.html

**Comment by saimedhi** [comment] 2023-09-27 22:56
Hello @ofirt-orca, I've reproduced the issue, but I'm not observing any errors. Please inform me if I've overlooked any details. Thanks :)



<img width="907" alt="Screenshot 2023-09-27 at 3 48 20 PM" src="https://github.com/opensearch-project/opensearch-py/assets/117196660/9f7a4369-0687-48c6-8a69-0ecb56758386">
<img width="779" alt="Screenshot 2023-09-27 at 3 50 28 PM" src="https://github.com/opensearch-project/opensearch-py/assets/117196660/21aebe1d-140e-4151-8967-dbd15b228104">
<img width="783" alt="Screenshot 2023-09-27 at 3 52 15 PM" src="https://github.com/opensearch-project/opensearch-py/assets/117196660/523dfb7a-bea2-49e9-b872-56279423166f">

**Comment by saimedhi** [comment] 2023-09-27 22:59
I'm closing this issue. If you believe it's still unresolved, please feel free to reopen it.

**Comment by ofirt-orca** [comment] 2023-09-28 03:46
Hi @saimedhi, it is not working only when working with AWS OpenSearch service.
Added code snippet. Can you reopen the issue?

`    
    import boto3
    from opensearchpy import OpenSearch, RequestsHttpConnection, AWSV4SignerAuth

    creds = boto3.Session().get_credentials()
    awsauth = AWSV4SignerAuth(creds, "us-east-1", "es")

    host = "xxxx.us-east-1.es.amazonaws.com"
    repo_name = "cs-automated-enc"
    snapshot_id = "snapshot-id"
    body = {
        'indices': 'index_123', 
    }

    os = OpenSearch(
        hosts=[{"host": host, "port": 80}],
        connection_class=RequestsHttpConnection,
        use_ssl=False,
        verify_certs=False,
        timeout=30,
        retry_on_timeout=True,
        http_compress=True,
        http_auth=awsauth,
    )

    os.snapshot.restore(repository=repo_name, snapshot=snapshot_id, body=body)
`

**Comment by saimedhi** [comment] 2023-09-28 18:52
@ofirt-orca, Could you please share the error details, and have you tested the code without AWS? 

- Additionally, does your code function correctly without using http_compress?
- Could you kindly confirm whether 'http_compress' has been passed as a parameter or a header?

**Comment by ofirt-orca** [comment] 2023-09-28 19:55
Sure, I'll try to provide code with creation soon, I'll need to create another OpenSearch cluster for that.
I use the python client to work with AWS OpenSearch cluster and everything works well with or without http compression besides this endpoint. It might be that even snapshot creation will fail with the same error.
This code works perfectly when http_compress is not set or False

**Comment by ofirt-orca** [comment] 2023-09-30 13:22
I've chosen another approach for reproduction since creating a snapshot will require setting up a manual repository, s3 bucket, roles and more. Instead, it can be reproduced by trying to restore an existing automated snapshot that should exist by default on either `cs-automated` or `cs-automated-enc` repositories. Try this code, let me know if it worked.

```
    import boto3
    from opensearchpy import OpenSearch, RequestsHttpConnection, AWSV4SignerAuth

    host = "xxxx.us-east-1.es.amazonaws.com"
    creds = boto3.Session().get_credentials()
    awsauth = AWSV4SignerAuth(creds, "us-east-1", "es")

    os = OpenSearch(
        hosts=[{"host": host, "port": 80}],
        connection_class=RequestsHttpConnection,
        use_ssl=False,
        verify_certs=False,
        timeout=30,
        retry_on_timeout=True,
        http_compress=True,
        http_auth=awsauth,
    )

    repo_name = "cs-automated-enc"
    snapshots = os.snapshot.get(repository=repo_name, snapshot=["*"])
    snapshot = snapshots["snapshots"][0]
    snapshot_id = snapshot["snapshot"]
    index = snapshot["indices"][0]

    body = {
        'indices': index, 
        'include_global_state': False, 
    }

    print(f"Restoring index {index} from snapshot {snapshot_id}")
    os.snapshot.restore(repository=repo_name, snapshot=snapshot_id, body=body)
```

**Comment by ofirt-orca** [comment] 2023-10-09 15:22
Hi @saimedhi, were you able to reproduce the issue using the code snippet?

**Comment by dblock** [comment] 2023-10-18 19:31
@ofirt-orca I don't think anyone is working on this. Am I understanding correctly that the issue is with Amazon OpenSearch Service, or is it a client-side problem? If it's the former (AOS), then we/you should open a ticket with Amazon. If it's a client problem help narrow it down and let us help you fix it here?

**Comment by ofirt-orca** [comment] 2023-10-21 08:24
@dblock seems like a server side bug of OpenSearch service. Would you mind opening an issue for them?

**Comment by dblock** [comment] 2023-10-23 15:18
I sent it to the right people, but it would be most effective if you could open a support ticket for your domain details.

Since this is AOS and not a client problem I'm going to close it here.

**Closed by dblock** 2023-10-23 15:18 UTC
Labels: bug
