### ISSUE TITLE
[BUG] Bulk request not throwing error

### ISSUE THREAD

**Issue by Xuton** [opensearch-project/opensearch-py#84] opened 2021-10-18 01:53 UTC
**What is the bug?**
When using the bulk request and an indexing error occurs, the error is not thrown. I have to assign the response and then manually check the response for errors.
When indexing documents using the single index method it does raise the error as expected

**How can one reproduce the bug?**
Steps to reproduce the behaviour:
Using an AWS hosted Elasticsearch V7.10 cluster
```
Create a client
client=OpenSearch(
    hosts=[{'host': host, 'port': port}],
    http_compress=True, # enables gzip compression for request bodies
    http_auth=auth,
    use_ssl=True,
    verify_certs=True,
    ssl_assert_hostname=False,
    ssl_show_warn=False,
    ca_certs=ca_certs_path
)

try:
     client.bulk(docs)
except TransportError as e:
    print(e)
```

**What is the expected behaviour?**
if there was an error indexing any of the documents, the catch should trigger. In my test I found the error `mapper_parsing_exception`, but since the error isn't thrown, its not possible to catch it (without manually inspecting the response)

When using the index method, the error is caught though eg
```
# Try and index the doc
try:
    client.index(
        index='Index_name`,
        body=body,
        id=123,
    )

except Exception as e:
    print(e.info['error']['caused_by'])
```

This will raise a TransportError which is caught by the Exception

**Comment by axeoman** [comment] 2021-12-28 10:54
I would argue with the proposed expected behaviour:
- Transport is actually fine in both examples, the `RequestError` should be raised when `mapper_parsing_exception` occurs.
- The `client.bulk` is something pretty raw and I would not change its behaviour because part of the requests can be succeded and part not, so raising an exception if it is at least one request failed - does not sound reasonable for me.
- For a nicer interface to a bulk operation, I would rather use [`helpers.bulk` ](https://github.com/opensearch-project/opensearch-py/blob/85b49ac228bb2e49bb920e3198fab729b11c37f1/opensearchpy/helpers/actions.py#L374) which will return a list of errors if there were some.

**Comment by wbeckler** [comment] 2022-08-05 05:49
axeoman's argument sounds definitive to me. I would propose closing this as "working as it should" if there aren't any objections.

**Comment by dblock** [comment] 2022-08-08 20:42
Let's ensure this is thoroughly documented before closing?

**Comment by dblock** [comment] 2023-07-26 14:27
I've documented error handling differences between `client.bulk` and `helpers.bulk` in https://github.com/opensearch-project/opensearch-py/blob/main/guides/bulk.md.

**Closed by dblock** 2023-07-26 14:27 UTC
Labels: documentation, question
