### ISSUE TITLE
[BUG] Link checker fails when adding relative URLs

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-py#538] opened 2023-10-13 18:19 UTC
### What is the bug?

Coming from https://github.com/opensearch-project/opensearch-py/pull/537/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 the link checker does not like `[page](link)` when link is a relative link to source code. These work on GitHub.

### How can one reproduce the bug?

- If you add a relative link, CI will fail on it as in https://github.com/opensearch-project/opensearch-py/actions/runs/6509630345/job/17681533560

```
### Errors in docs/source/README.md
* [file:///home/runner/work/opensearch-py/opensearch-py/docs/source/samples](file:///home/runner/work/opensearch-py/opensearch-py/docs/source/samples): Failed: Cannot find file
* [file:///home/runner/work/opensearch-py/opensearch-py/docs/source/benchmarks](file:///home/runner/work/opensearch-py/opensearch-py/docs/source/benchmarks): Failed: Cannot find file
```

- If you add a new link to something that doesn't exist, CI will fail on it as in https://github.com/opensearch-project/opensearch-py/actions/runs/6511677337/job/17687825863?pr=537

```
### Errors in README.md
* [https://github.com/opensearch-project/opensearch-py/tree/main/benchmarks](https://github.com/opensearch-project/opensearch-py/tree/main/benchmarks): Failed: Network error
```

### What is the expected behavior?

- Allow one to add a new relative link.
- Link checker should pass.

**Comment by saimedhi** [comment] 2023-10-13 18:22
I think the problem is not with link checker. We have a copy of README.md in docs/source. That is causing problem when relative path is given.

**Comment by dblock** [comment] 2023-10-13 18:23
> I think the problem is not with link checker. We have a copy of README.md in docs/source. That is causing problem when relative path is given.

Oh! It's a soft link too, not a copy!

**Comment by Krish-2505** [comment] 2024-06-06 17:39
<img width="507" alt="image" src="https://github.com/opensearch-project/opensearch-py/assets/120018777/fc3bd798-283b-4ead-9286-b5e2c9bf74e5">
<img width="529" alt="image" src="https://github.com/opensearch-project/opensearch-py/assets/120018777/8ee25917-0dc0-4a3c-b6cf-99414584be16">

I cannot see logs from these links, maybe the logs are expired. so it will be helpful for me to contribute if you can provide some context/screenshots of these logs.

**Comment by dblock** [comment] 2024-06-07 12:31
@Krish-2505 add a relative link to any doc and submit a draft PR, it should fail.

**Comment by Krish-2505** [comment] 2024-06-10 05:37
@dblock I attempted to include a relative link, but the link checker did not detect any failures. it detected failures when I added a link that didn't exist.

**Comment by Krish-2505** [comment] 2024-06-10 06:00
<img width="820" alt="image" src="https://github.com/opensearch-project/opensearch-py/assets/120018777/9f9ec35f-143a-491e-9ffe-705401e1ba5f">  
@dblock In the file DEVELOPER_GUIDE.md, the link highlighted in yellow does not exist, and the link checker is failing because of this non-existent link. However, the link checker is not failing for the other relative links that were added to any doc.

**Comment by dblock** [comment] 2024-06-10 13:04
I don't see a relative link in your draft PR (https://github.com/opensearch-project/opensearch-py/pull/758), show me a passing link checker on a relative link?

**Comment by Krish-2505** [comment] 2024-06-10 17:36
<img width="891" alt="image" src="https://github.com/opensearch-project/opensearch-py/assets/120018777/60b7a3ab-8e2c-4174-8126-4f83c96779ce">
<img width="581" alt="image" src="https://github.com/opensearch-project/opensearch-py/assets/120018777/7ba9d2f8-3ddd-439b-8837-42f1cbecf492">
Here I added one relative link in readme.md in the forked repo and created a pull request,  link checker didn't fail here

**Comment by dblock** [comment] 2024-06-10 17:40
@Krish-2505 can you please post a link to this change, not a screenshot?

**Comment by Krish-2505** [comment] 2024-06-11 06:09
@dblock  https://github.com/Krish-2505/opensearch-py/pull/4

**Comment by dblock** [comment] 2024-06-11 12:23
@Krish-2505 That's not a relative link.

```
[https://github.com/opensearch-project/opensearch-py/tree/main/benchmarks](https://github.com/opensearch-project/opensearch-py/tree/main/benchmarks)
```

A relative link to `https://github.com/opensearch-project/opensearch-py/tree/main/benchmarks` from `https://github.com/opensearch-project/opensearch-py/` would be `benchmarks`.

```
[link](benchmarks)
```

**Comment by Krish-2505** [comment] 2024-06-12 14:21
@dblock @dblock The link checker is encountering an issue when adding relative links to the README.md file. It seems that the link checker is resolving the relative links incorrectly due to the presence of a soft copy of the README.md file in the docs/source directory.
Specifically, when adding a relative link to the README.md file (as shown in this (https://github.com/Krish-2505/opensearch-py/actions/runs/9484199895/job/26133143647)), the link checker fails because it's attempting to resolve the relative link relative to the docs/source directory instead of the repository root.
However, when adding a relative link to the developers_guide.md file (as shown in this (https://github.com/Krish-2505/opensearch-py/pull/3)), the link checker does not encounter any issues.
so, i think problem occurs due to soft copy of readme file

**Comment by dblock** [comment] 2024-06-12 14:41
Yes, this is the problem that needs fixing as pointed out by @saimedhi in https://github.com/opensearch-project/opensearch-py/issues/538#issuecomment-1761987524.

**Comment by Krish-2505** [comment] 2024-06-13 08:57
@dblock I've made modifications to the links.yml workflow file to address the issue with relative links in the README.md.

Here's a summary of the changes:

<img width="229" alt="image" src="https://github.com/opensearch-project/opensearch-py/assets/120018777/f84bce68-635a-41fa-a10f-570db294690f">

Added a new step before the link checking process. This step removes the symbolic link (soft link) of README.md in the docs/source directory. This prevents the link checker from incorrectly resolving relative links due to the presence of this soft copy.

<img width="481" alt="image" src="https://github.com/opensearch-project/opensearch-py/assets/120018777/434f38f0-c71b-4133-9b0c-0b3bcb6903be">

In the arguments section of the lychee Link Checker, I've added an exclusion for the file reference to the docs/source/README.md. This exclusion is necessary because even though we've removed the soft link, other parts of the project or external references might still point to this location. By excluding it from the link check, we ensure that the checker doesn't attempt to validate any links that might reference this now-nonexistent soft link. This prevents potential false positives or errors that could arise from references to the removed soft link.

<img width="284" alt="image" src="https://github.com/opensearch-project/opensearch-py/assets/120018777/c8709a2e-66f6-423d-b3f9-d8bd67d71ed9">

After the link checking is complete, I've added another step to recreate the soft link. This ensures that the repository structure remains intact and doesn't affect other workflows that might depend on the presence of this soft link.

After making these change link checker is working as Expected. Check out this pr(https://github.com/Krish-2505/opensearch-py/pull/5). links.yml(https://github.com/Krish-2505/opensearch-py/edit/main/.github/workflows/links.yml)

**Comment by dblock** [comment] 2024-06-13 14:28
@Krish-2505 Make a PR into this project and I can take a look?

**Closed** 2024-06-18 14:59 UTC
Labels: bug, good first issue
